#!/usr/bin/env node
/**
 * Summarize imported-edit smoke performance without copying private sheet text.
 *
 * Input is the local-only `imported-edit-sync-results.json` generated by
 * scripts/imported_edit_sync_smoke.mjs. Output contains fixture id, timings,
 * block counts, drift, and pass/warn/fail status only. It intentionally omits
 * HTML snippets, CSS snippets, DOM text, screenshots, and resource URLs.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';

const args = process.argv.slice(2);

function argOf(name, fallback) {
  const i = args.indexOf(name);
  return i >= 0 && args[i + 1] ? args[i + 1] : fallback;
}

function hasFlag(name) {
  return args.includes(name);
}

const RESULTS = path.resolve(argOf('--results', 'reports/imported-edit-sync/imported-edit-sync-results.json'));
const OUT_JSON = argOf('--out-json', '');
const OUT_MD = argOf('--out-md', '');
const REDACT_IDS = argOf('--redact-ids', 'false') === 'true';
const FAIL_ON_BUDGET = hasFlag('--fail-on-budget') || argOf('--fail-on-budget', 'false') === 'true';

const BUDGETS = {
  importTotalMs: { warn: 6000, fail: 10000 },
  injectMs: { warn: 5000, fail: 8000 },
  emitMs: { warn: 200, fail: 500 },
  dragDriftPx: { warn: 1, fail: 2 },
  pageErrors: { warn: 1, fail: 1 },
  resourceWarnings: { warn: 1, fail: 999999 },
};

function statusFor(value, budget) {
  if (value == null || Number.isNaN(value)) return 'UNKNOWN';
  if (value >= budget.fail) return 'FAIL';
  if (value >= budget.warn) return 'WARN';
  return 'PASS';
}

function worstStatus(statuses) {
  if (statuses.includes('FAIL')) return 'FAIL';
  if (statuses.includes('UNKNOWN')) return 'UNKNOWN';
  if (statuses.includes('WARN')) return 'WARN';
  return 'PASS';
}

function fixtureLabel(id, index) {
  return REDACT_IDS ? `fixture-${index + 1}` : id;
}

function firstPassingAttempt(fixture) {
  return fixture.attempts?.find((attempt) => attempt.pass) ?? fixture.attempts?.[0] ?? null;
}

function summarizeFixture(fixture, index) {
  const attempt = firstPassingAttempt(fixture);
  const timeline = attempt?.dragTimeline ?? null;
  const drift = Math.max(timeline?.leftDrift ?? 0, timeline?.topDrift ?? 0);
  const resourceWarnings = fixture.resourcePass === false ? 1 : 0;
  const pageErrors = fixture.pageErrors?.length ?? 0;
  const importTotalMs = round(fixture.import?.totalMs);
  const injectMs = round(fixture.import?.injectMs);
  const emitMs = round(fixture.import?.emitMs);
  const htmlShape = fixture.htmlWorkspaceShape ?? {};
  const largestRoot = htmlShape.roots?.[0] ?? null;
  const topRemainingTrSignature = htmlShape.remainingTrSignatures?.[0] ?? null;
  const estimatedWideRowReduction =
    typeof topRemainingTrSignature?.totalDescendantBlocks === 'number' &&
    typeof topRemainingTrSignature?.rowCount === 'number'
      ? Math.max(0, topRemainingTrSignature.totalDescendantBlocks - topRemainingTrSignature.rowCount)
      : null;
  const projectedHtmlBlocksWithTopRowBundle =
    typeof fixture.import?.blockCount === 'number' && typeof estimatedWideRowReduction === 'number'
      ? Math.max(0, fixture.import.blockCount - estimatedWideRowReduction)
      : null;
  const statuses = {
    interaction: fixture.interactionPass ? 'PASS' : 'FAIL',
    importTotalMs: statusFor(importTotalMs, BUDGETS.importTotalMs),
    injectMs: statusFor(injectMs, BUDGETS.injectMs),
    emitMs: statusFor(emitMs, BUDGETS.emitMs),
    dragDriftPx: statusFor(drift, BUDGETS.dragDriftPx),
    pageErrors: statusFor(pageErrors, BUDGETS.pageErrors),
    resourceWarnings: statusFor(resourceWarnings, BUDGETS.resourceWarnings),
  };

  return {
    id: fixtureLabel(fixture.id ?? `fixture-${index + 1}`, index),
    sourceIdRedacted: REDACT_IDS,
    status: worstStatus(Object.values(statuses)),
    statuses,
    metrics: {
      blockCount: fixture.import?.blockCount ?? null,
      workerBlockCount: fixture.import?.workerBlockCount ?? null,
      rootHtmlBlocks: fixture.workspaceAfterImport?.rootBlocks?.html ?? null,
      totalWorkspaceBlocks: fixture.workspaceAfterImport?.totalBlocks ?? null,
      htmlRootBlocks: htmlShape.rootBlocks ?? fixture.workspaceAfterImport?.rootBlocks?.html ?? null,
      largestRootSubtreeBlocks: htmlShape.largestRootSubtreeBlocks ?? null,
      largestRootSubtreePct: htmlShape.largestRootSubtreePct ?? null,
      largestRootType: largestRoot?.rootType ?? null,
      largestRootMaxDepth: largestRoot?.maxDepth ?? null,
      largestRootTopTypes: Array.isArray(largestRoot?.topTypes) ? largestRoot.topTypes : [],
      compositeCollapsed: fixture.import?.compositeCollapsed ?? null,
      compositePackedByType: fixture.import?.compositePackedByType ?? {},
      wideRowBundles: fixture.import?.wideRowBundles ?? null,
      wideRowCollapsed: fixture.import?.wideRowCollapsed ?? null,
      topRemainingTrRows: topRemainingTrSignature?.rowCount ?? null,
      topRemainingTrDescendantBlocks: topRemainingTrSignature?.totalDescendantBlocks ?? null,
      topRemainingTrAvgBlocks: topRemainingTrSignature?.avgDescendantBlocks ?? null,
      topRemainingTrMaxBlocks: topRemainingTrSignature?.maxDescendantBlocks ?? null,
      topRemainingTrTypes: Array.isArray(topRemainingTrSignature?.topTypes) ? topRemainingTrSignature.topTypes : [],
      estimatedWideRowReduction,
      projectedHtmlBlocksWithTopRowBundle,
      importTotalMs,
      parseMs: round(fixture.import?.parseMs),
      injectMs,
      emitMs,
      dragDriftPx: drift,
      dragTimelineSamples: timeline?.samples?.length ?? 0,
      editPreviewSync: Boolean(fixture.pass && fixture.interactionPass),
      reimportStable: Boolean(fixture.reimport?.stable?.html && fixture.reimport?.stable?.css && fixture.reimport?.stable?.i18n),
      resourceWarnings,
      consoleErrors: fixture.consoleErrors?.length ?? 0,
      pageErrors,
    },
  };
}

function round(value) {
  return typeof value === 'number' && Number.isFinite(value) ? Math.round(value * 10) / 10 : null;
}

function fmtTypeCounts(counts) {
  if (!counts || typeof counts !== 'object') return '';
  return Object.entries(counts)
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([type, count]) => `${type}:${count}`)
    .join('<br>');
}

function renderMarkdown(summary) {
  const lines = [];
  lines.push('# Imported Edit Performance Budget');
  lines.push('');
  lines.push(`Generated: ${summary.generatedAt}`);
  lines.push(`Source: \`${summary.source}\``);
  lines.push(`Overall: **${summary.status}**`);
  lines.push('');
  lines.push('| Fixture | Status | Blocks | Root HTML | Max root subtree | Max root % | Max root depth | Composite collapsed | Composite types | Wide row bundles | Wide row collapsed | Top row sig rows | Top row sig blocks | Est. row reduction | Projected HTML blocks | Import ms | Inject ms | Emit ms | Drift px | Sync | Reimport | Resources | Page errors |');
  lines.push('|---|---:|---:|---:|---:|---:|---:|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|---|---|---:|');
  for (const item of summary.fixtures) {
    const m = item.metrics;
    lines.push([
      `\`${item.id}\``,
      item.status,
      m.blockCount ?? '',
      m.rootHtmlBlocks ?? '',
      m.largestRootSubtreeBlocks ?? '',
      m.largestRootSubtreePct ?? '',
      m.largestRootMaxDepth ?? '',
      m.compositeCollapsed ?? '',
      fmtTypeCounts(m.compositePackedByType),
      m.wideRowBundles ?? '',
      m.wideRowCollapsed ?? '',
      m.topRemainingTrRows ?? '',
      m.topRemainingTrDescendantBlocks ?? '',
      m.estimatedWideRowReduction ?? '',
      m.projectedHtmlBlocksWithTopRowBundle ?? '',
      m.importTotalMs ?? '',
      m.injectMs ?? '',
      m.emitMs ?? '',
      m.dragDriftPx ?? '',
      m.editPreviewSync ? 'PASS' : 'FAIL',
      m.reimportStable ? 'PASS' : 'WARN',
      item.statuses.resourceWarnings,
      m.pageErrors ?? '',
    ].join(' | ').replace(/^/, '| ').replace(/$/, ' |'));
  }
  lines.push('');
  lines.push('## Budgets');
  lines.push('');
  lines.push(`- Import total: WARN >= ${BUDGETS.importTotalMs.warn}ms, FAIL >= ${BUDGETS.importTotalMs.fail}ms`);
  lines.push(`- Blockly inject: WARN >= ${BUDGETS.injectMs.warn}ms, FAIL >= ${BUDGETS.injectMs.fail}ms`);
  lines.push(`- Emit: WARN >= ${BUDGETS.emitMs.warn}ms, FAIL >= ${BUDGETS.emitMs.fail}ms`);
  lines.push(`- Drag drift: WARN >= ${BUDGETS.dragDriftPx.warn}px, FAIL >= ${BUDGETS.dragDriftPx.fail}px`);
  lines.push('- Shape metrics are sanitized structural counts only. They omit block IDs, DOM text, HTML snippets, CSS snippets, and private fixture paths.');
  lines.push('- Estimated row reduction is a dry-run unless the fixture was imported with `--compact-wide-rows true`; wide row bundle metrics report actual optional compaction.');
  lines.push('- Wide row compaction preserves rendered HTML rows as raw bundles, but direct block editing inside each bundled row is limited until a future ungroup/lazy-materialization path exists.');
  lines.push('');
  lines.push('Claim boundary: this report measures local imported edit performance only. It does not prove Roll20 visual parity.');
  lines.push('');
  return `${lines.join('\n')}\n`;
}

async function writeIfRequested(file, content) {
  if (!file) return;
  const target = path.resolve(file);
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, content, 'utf8');
}

async function main() {
  const raw = JSON.parse(await fs.readFile(RESULTS, 'utf8'));
  const fixtures = (raw.fixtures ?? []).map(summarizeFixture);
  const summary = {
    generatedAt: new Date().toISOString(),
    source: REDACT_IDS ? path.basename(RESULTS) : RESULTS,
    status: worstStatus(fixtures.map((item) => item.status)),
    budgets: BUDGETS,
    fixtures,
  };

  const json = JSON.stringify(summary, null, 2);
  await writeIfRequested(OUT_JSON, `${json}\n`);
  await writeIfRequested(OUT_MD, renderMarkdown(summary));
  console.log(json);

  if (FAIL_ON_BUDGET && summary.status === 'FAIL') {
    process.exitCode = 1;
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
